export const WORLD = {
  sx: 56,
  sy: 14,
  sz: 48,
  originX: -28,
  originY: 0,
  originZ: -30,
}

export const MAT = {
  AIR: 0,
  FLOOR: 1,
  WALL: 2,
  SOLID: 3,
  NEON: 4,
}

export const LOOK = {
  bg: 0x020508,
  fogNear: 16,
  fogFar: 52,
  bloomStrength: 1.22,
  bloomRadius: 0.54,
  bloomThreshold: 0.14,
  exposure: 0.82,
  fov: 58,
}

export const PLAYER = {
  runSpeed: 7.4,
  accel: 28,
  airAccel: 10,
  gravity: 28,
  jumpV: 8.6,
  dashSpeed: 19,
  dashTime: 0.16,
  dashCooldown: 0.62,
  coyote: 0.1,
  halfW: 0.38,
  height: 1.62,
  eye: 1.42,
  camDist: 3.38,
  camShoulder: 0.98,
  camHeight: 1.52,
  mouseSens: 0.00215,
}

export const WEAPONS = [
  {
    id: 'cannon',
    name: 'VX-9 HAND CANNON',
    mag: 10,
    rpm: 150,
    reload: 1.15,
    dmg: 18,
    spread: 0.004,
    pellets: 1,
    hitscan: true,
    carve: 0,
    dummyRadius: 0.55,
    auto: false,
    crosshair: 'cannon',
    color: 0xff7a18,
  },
  {
    id: 'autogun',
    name: 'VX-24 AUTOGUN',
    mag: 24,
    rpm: 720,
    reload: 1.35,
    dmg: 6,
    spread: 0.014,
    pellets: 1,
    hitscan: true,
    carve: 0,
    dummyRadius: 0.42,
    auto: true,
    tracer: 0xff3a18,
    crosshair: 'auto',
    color: 0xff3a2a,
  },
  {
    id: 'scattergun',
    name: 'VX-8 SCATTERGUN',
    mag: 6,
    rpm: 88,
    reload: 1.55,
    dmg: 5,
    spread: 0.078,
    pellets: 8,
    hitscan: true,
    carve: 0,
    dummyRadius: 0.5,
    auto: false,
    crosshair: 'spread',
    color: 0xffc14a,
  },
  {
    id: 'blockbuster',
    name: 'VX-R7 BLOCKBUSTER',
    mag: 3,
    rpm: 52,
    reload: 1.8,
    dmg: 80,
    spread: 0,
    pellets: 1,
    hitscan: false,
    speed: 32,
    radius: 2.6,
    dummyRadius: 2.2,
    auto: false,
    crosshair: 'rocket',
    color: 0xff9a1a,
  },
]

export const DUMMY = {
  respawn: 6.2,
  flashMs: 90,
  voxel: 0.2,
  depth: 1,
}
